# Generated by Django 3.2.4 on 2021-06-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='is_completed',
        ),
    ]
